// Shared UI/API catalog only; statistical detector stays on the server.
export const languageCodes = [
  "en",
  "ru",
  "kk",
  "uk",
  "es",
  "pt",
  "fr",
  "de",
  "it",
  "tr",
  "ar",
  "hi",
  "zh",
  "ja",
  "ko",
  "und",
] as const;
export const languageLabels: Record<(typeof languageCodes)[number], string> = {
  en: "English",
  ru: "Russian",
  kk: "Kazakh",
  uk: "Ukrainian",
  es: "Spanish",
  pt: "Portuguese",
  fr: "French",
  de: "German",
  it: "Italian",
  tr: "Turkish",
  ar: "Arabic",
  hi: "Hindi",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  und: "Undetermined",
};
