/** Stripe invoice/charge units, not payout or generic ISO currency exponents.
 * Source: https://docs.stripe.com/currencies (reviewed 2026-10-07).
 */
const zeroDecimal = new Set([
  "bif",
  "clp",
  "djf",
  "gnf",
  "jpy",
  "kmf",
  "krw",
  "mga",
  "pyg",
  "rwf",
  "vnd",
  "vuv",
  "xaf",
  "xof",
  "xpf",
]);
// ISK/UGX have no charge fractions but retain a /100 API representation.
const wholeWithHundredUnits = new Set(["isk", "ugx"]);
const twoDecimal = new Set([
  "usd",
  "aed",
  "afn",
  "all",
  "amd",
  "ang",
  "aoa",
  "ars",
  "aud",
  "awg",
  "azn",
  "bam",
  "bbd",
  "bdt",
  "bmd",
  "bnd",
  "bob",
  "brl",
  "bsd",
  "bwp",
  "byn",
  "bzd",
  "cad",
  "cdf",
  "chf",
  "cny",
  "cop",
  "crc",
  "cve",
  "czk",
  "dkk",
  "dop",
  "dzd",
  "egp",
  "etb",
  "eur",
  "fjd",
  "fkp",
  "gbp",
  "gel",
  "gip",
  "gmd",
  "gtq",
  "gyd",
  "hkd",
  "hnl",
  "htg",
  "huf",
  "idr",
  "ils",
  "inr",
  "jmd",
  "kes",
  "kgs",
  "khr",
  "kyd",
  "kzt",
  "lak",
  "lbp",
  "lkr",
  "lrd",
  "lsl",
  "mad",
  "mdl",
  "mkd",
  "mmk",
  "mnt",
  "mop",
  "mur",
  "mvr",
  "mwk",
  "mxn",
  "myr",
  "mzn",
  "nad",
  "ngn",
  "nio",
  "nok",
  "npr",
  "nzd",
  "pab",
  "pen",
  "pgk",
  "php",
  "pkr",
  "pln",
  "qar",
  "ron",
  "rsd",
  "rub",
  "sar",
  "sbd",
  "scr",
  "sek",
  "sgd",
  "shp",
  "sle",
  "sos",
  "srd",
  "std",
  "szl",
  "thb",
  "tjs",
  "top",
  "try",
  "ttd",
  "twd",
  "tzs",
  "uah",
  "uyu",
  "uzs",
  "wst",
  "xcd",
  "xcg",
  "yer",
  "zar",
  "zmw",
]);
export function formatStripeInvoiceAmount(
  amount: number,
  currency: string,
): string {
  if (
    !Number.isSafeInteger(amount) ||
    amount < 0 ||
    !/^[a-z]{3}$/i.test(currency)
  )
    return "Unavailable";
  const code = currency.toLowerCase();
  const label = code.toUpperCase();
  if (zeroDecimal.has(code)) return `${amount} ${label}`;
  if (!twoDecimal.has(code) && !wholeWithHundredUnits.has(code))
    return `${amount} minor units (${label})`;
  // Split the integer directly: no floating-point rounding of large amounts.
  const whole = Math.floor(amount / 100);
  const fraction = amount % 100;
  if (wholeWithHundredUnits.has(code) && fraction === 0)
    return `${whole} ${label}`;
  return `${whole}.${String(fraction).padStart(2, "0")} ${label}`;
}
